version: '2'
services:

  django:
    container_name: vaico-snakes
    build:
      context: .
    networks:
      - vaico-django-nginx
    volumes:
      - vaico-django-static:/usr/src/app/vaicoSnakes/static
    ports:
      - 8000:8000

  nginx:
    container_name: vaico-nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    networks:
      - vaico-django-nginx
    volumes:
      - vaico-django-static:/usr/src/app/static
      - vaico-nginx-cert:/etc/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django

volumes:
  vaico-django-static:
  vaico-nginx-cert:
      
networks:
  vaico-django-nginx:
    driver: bridge