version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=my_awesome_project
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"
      
  web:
    build: vaicoSnakes
    command: bash -c "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')\" | python manage.py shell && python /code/manage.py makemigrations && python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./vaicoSnakes:/code
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/my_awesome_project
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
      - rabbitmq
      
  celery:
    build: vaicoSnakes
    command: celery -A vaicoSnakes worker -l info
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/my_awesome_project
    volumes:
      - ./vaicoSnakes:/code
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: